name: sequence-localization-env
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - bleach
  - libffi
  - python-dateutil
  - appnope
  - backports
  - backports.functools_lru_cache
  - backports.shutil_get_terminal_size
  - backports_abc
  - ca-certificates
  - certifi
  - configparser
  - cycler
  - dbus
  - decorator
  - entrypoints
  - enum34
  - expat
  - freetype
  - functools32
  - gettext
  - glib
  - html5lib
  - icu
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - libcxx
  - libcxxabi
  - libedit
  - libgfortran
  - libiconv
  - libpng
  - libsodium
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - pathlib2
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pip
  - prompt_toolkit
  - ptyprocess
  - pygments
  - pyparsing
  - pyqt
  - python
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - readline
  - scandir
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - simplegeneric
  - singledispatch
  - sip
  - six
  - sqlite
  - ssl_match_hostname
  - statsmodels
  - subprocess32
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xarray
  - xlrd
  - zeromq
  - zlib
  - pip:
    - backports.ssl-match-hostname
    - pronto
